#!/bin/bash

apt-get install -y openjdk-11-jdk

apt install -y mysql-server

apt-get install -y redis-server

wget https://mirror.navercorp.com/apache/kafka/2.8.0/kafka_2.13-2.8.0.tgz

tar xvf kafka_2.13-2.8.0.tgz

mv kafka_2.13-2.8.0/ kafka

wget https://github.com/yahoo/CMAK/releases/download/3.0.0.5/cmak-3.0.0.5.zip

unzip cmak-3.0.0.5.zip

mv cmak-3.0.0.5 cmak
